### ISSUE TITLE
Suggetion

### ISSUE THREAD

**Issue by unawake** [razeenf/Price-Tracker-Bot#1]
What would I have to do in order to track everything on amazon
like price errors and deals without manually listing an item you want to track

**Comment by razeenf** [comment]
Every Amazon product has a Amazon Standard Identification Number (ASIN) in the URL, so I used a web scraper to track the price for specific products using their ASIN, to do this with every product on Amazon might not work since there's so many.  Amazon does have an API that gives you access to product information however its not available for public use so I didn't look into it much further.
